---
name: Luisa M.
surname: Mimmi
position: Economist & Public Policy Advisor #"Economista & Analista di Politiche Pubbliche"
#address: EU citizen (Italy) | Green card holder
#www: lulliter.com
email: lmm76@georgetown.edu
linkedin: luisa-m-mimmi
#twitter: lulliter
github: lulliter
researchgate: Luisa-Mimmi
headcolor: 0088cc #cc0066 # 0088cc #0073e6 #990000
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: |-
  Experienced policy advisor with a strong background in statistical and econometric analysis applied to economic development. In over 15 years of experience in Italy and abroad, I have evaluated the feasibility and impact of policies and financial instruments promoting inclusive and sustainable access to infrastructure services (housing, mobility, water and sanitation, energy, education and health).  
  I am currently pursuing opportunities to apply my policy analysis and project management skills towards the implementation and evaluation of national & EU Structural and Investment Funds (PNRR, Next Generation EU, ERDF, ESF, CF, etc).
  
# profilepic: ../foto/LulaSalvador2015.jpg
docname: Curriculum Vitae
csl: apa6-cv.csl # no numbering in bib
output:
  vitae::awesomecv: 
  keep_tex: false
  latex_engine: "xelatex" # maybe redund bc in awsomecv is already this 
always_allow_html: yes
header-includes:
  \usepackage{float}
  \usepackage{multicol}
  \usepackage{colortbl}
  \arrayrulecolor{white}
  \usepackage{hhline}
  \definecolor{light-gray}{gray}{0.95}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

# if (cond) expr
if (!require("pacman")) install.packages("pacman")
p_load('vitae'     # The CV's LaTeX Template
       ,'tibble'    # Data structure for tribbles
       ,'dplyr' , 'ggplot2'
       ,'lubridate'
       ,'magrittr'  # The Pipe %>%
       ,'here'      # Relative File Paths
       ,'readr'     # Data Loading
       ,'glue'      # String Manipulation
       ,'rorcid'
       ,'RefManageR'
       ,'scholar'
       , 'emojifont'
       , 'fontawesome'
       , 'ggrepel' 
       ,'kableExtra'
       ,'huxtable'
       ,'gridExtra'
)

        # library(vitae)
        # library(ggplot2)
        # library(dplyr)
        # library(sf)
        # library(rworldmap)
        # library(stplanr)
        # library(ggrepel)
        # library(emojifont)
        # library(fontawesome)
        # library(kableExtra)
        # library(huxtable)
        # library(gridExtra)

#p_load_gh("rstudio", "fontawsome")

 # MODO ALTERNATIVO -----------------------
# require(xfun)
# packages <- c('vitae'     # The CV's LaTeX Template
#              ,'tibble'    # Data structure for tribbles
#              ,'dplyr' 
#              ,'lubridate'
#              ,'magrittr'  # The Pipe %>%
#              ,'here'      # Relative File Paths
#              ,'readr'     # Data Loading
#              ,'glue'      # String Manipulation
#              ,'rorcid'
#              ,'RefManageR'
#              ,'scholar'
#              )
# xfun::pkg_attach2(packages, message = FALSE)
 
# data input (in "./data/data_Lula.R")
source(file = here("data", "data_Lula.R")) # "data.r"


# rorcid_app <- httr::oauth_app(
#   appname = "rorcid",
#   key = "APP-7E02XXWNQBFNMG1B",
#   secret = "74c15780-e323-48a0-9296-ecceaf46e447"
# )

# ORCID_TOKEN <- Sys.getenv("ORCID_TOKEN") 

## -------- SPAZI 
# \bigskip
# \newpage
```

<!-- # Employment history -->

\faIcon{briefcase} Professional Experience
============================================

```{r employment, results='asis'}
# tribble(
#   ~Years, ~Position, ~Company,
#   '2018:...', "Research Fellow", "Inter-American Development Bank, (Washington DC)",
#   '2018:...', "Fundraising Data Analyst (Pro bono)", "New York Encounter, (remote)",
#   '2009:2018', "Senior M&E Specialist", "World Bank, Sustainable Development VP, (Washington DC)",
#   '2008' , "Policy Analyst", "Inter-American Development Bank, (Washington DC)",
#   '2007' , "Summer Intern", "AVSI International (Brazil)",
#   '2001:2006', "Business Intelligence Analyst", "Value Partners (Italy)",
#    ) %>%
#   # arrange(-Years) %>%
#    #filter(Start > 2000) %>%
#   # mutate(End = replace_na(End, "")) %>%
#   # mutate(Years = paste(Start, "--", End, sep = "")) %>%
#   select(Years, Position, Company ) %>%
#   detailed_entries(
#     when = Years, 
#     what = Position, 
#     where = Company )

work %>%
  vitae::detailed_entries(
    with =  unit , #scambiati x spazio
    what = title,
     why = detail,
    when = glue::glue("{startMonth} {startYear}-{endMonth} {endYear}",.na = ""),
    where = where #scambiati x spazio
  )
```

<!-- \faIcon{r-project}  Data Science Projects -->
<!-- =====================================  -->
```{r PROJECTS, eval=FALSE, include=FALSE}
# ~area,  ~year, ~accomplishment, ~where, ~link,
# projects %>%
# detailed_entries(
#     with = area,
#     when =  year,
#     what = accomplishment, 
#     # where = where,
#         why = link,
#         .protect = FALSE, # to turn link in LATEX 
#   )


#projects2 <- tibble::tribble(~name,  ~year, ~explain,
projects2 %>%
vitae::detailed_entries(
    what = name,
    when = year,
    #with = NA_character_,
    why = explain,
    #where = NA_character_,
    .protect = FALSE
  )

 
```


<!-- # Education -->
```{r education}
# edu <- rorcid::orcid_works("0000-0002-2244-8282")
# edu$`0000-0002-2244-8282`$`education-summary` %>%
#   detailed_entries(
#     what = `role-title`,
#     when = glue::glue("{`start-date.year.value`} - {`end-date.year.value`}"),
#     with = organization.name,
#     where = organization.address.city
#   )
```

<!-- \newpage -->

\endfirstpage



\faIcon{graduation-cap} Education
==================================
<!--  \faIcon{university} -->
```{r EDUCATION}
edu %>% 
  vitae::detailed_entries( with = inst,
    what = degree,
    why = detail,
    when =  ifelse(is.na(startYear),
                   endYear, glue::glue("{startYear}-{endYear}",.na = "")),
    where = where)
```



\faIcon{medal} Honors & Awards
=============================== 
```{r}
# ~area, ~accomplishment, ~year, ~where, [~detail],
honors %>%
  vitae::detailed_entries(
    # with = area,
    # what = accomplishment,
    what = where   ,
    when = year,
    with =glue::glue("{area}: {accomplishment}",.na = "" )
  )

# # try to make it less pompous
# honors %>% 
#   vitae::brief_entries(
#     #with = area,
#     what = glue::glue("{area} - {accomplishment}",.na = "" )  ,
#     #why = detail,
#     when = where ,
#     with = year
#   )
```


<!-- FOR THESE I AM NOT ACTUALLY USING data_Lula.R [I extract from .bib directly using `vitae::bibliography_entries` own function ] -->

\faBook[regular] Publications  
===========================
<!-- [_See detailed list on [**my Google Scholar Profile**](https://scholar.google.com/citations?user=OBYla5gAAAAJ&hl=en&oi=ao)_] -->

\bigskip

\faBookOpen[regular] Peer-Reviewed Articles & Technical Reports
---------------------------
[_See detailed list on [**Google Scholar Profile**](https://scholar.google.com/citations?user=OBYla5gAAAAJ&hl=en&oi=ao)_]

```{r PUBgooglesch}
# # from Google Scholar | not needed

# publicationsGSL  %>%
#   vitae::detailed_entries(
#     what = title,
#     when = year,
#     with = author,
#     where = journal #,
#     #why = glue::glue("citations: {cites}")
#   )
#     
```

```{r PUBzotero}
#not needed
# # from Synched Lula-MyPublications-Narrow.bib (in Zotero)
# author, title, type, issued, journal
 
 # vitae::bibliography_entries(file = here::here("data", "Lula-MyPublication-Narrow.bib")
 #                             # ,sorting="ydnt"
 #                              )  %>% 
#  select(-genre) %>%  
 #  arrange(desc(issued)) %>% 
 #  filter( stringr::str_detect(type ,"webpage" , negate = TRUE)  )
 
```

<!-- \medskip -->

\faIcon{rss} Other Media
---------------------------
[_See detailed list on [**Personal Website**](https://lulliter.com/publications.html#misc.-divulgative-pieces)_]

<!-- \faIcon{file-signature} -->
```{r BLOGzotero, eval=FALSE, include=FALSE}
# # from Synched Lula-MyPublications-Narrow.bib (in Zotero)
# author, title, type, issued, journal
 
#print<-  
vitae::bibliography_entries(file = here::here("data", "Lula-MyPublication-Narrow.bib")
                            # ,sorting="ydnt"
)  %>% 
  select(-genre) %>%  
  arrange(desc(issued)) %>% 
  filter( stringr::str_detect(type ,"webpage" )  )
 

# --------- names(print)
#   "URL" "author"  "genre" "id" "issued" "keyword" "language"  "publisher"  "title"            "title-short"  "type" "DOI" "ISSN" "accessed" "container-title"  "issue""page" "volume"           "abstract"  "collection-title" "number" "publisher-place"  "annote"  

# --------- print$type
# "webpage" "webpage" "report" "webpage" "webpage" "article-journal" "report"         
#  [8] "report"          "report"          "article-journal" "report"          "webpage"     
```


<!-- \faIcon*{calendar} Talks -->
<!-- =========================== -->

<!-- ```{r TALKzotero} -->
<!-- # # from Synched Lula-MyTalks.bib (in Zotero) -->
<!-- # author, title, type, issued, journal -->

<!--   vitae::bibliography_entries(file = here::here("data", "Lula-MyTalks.bib") -->
<!--                              # ,sorting="ydnt" -->
<!--                               )  %>% -->
<!--   select(-genre) %>% -->
<!--   arrange(desc(issued)) -->

<!-- ``` -->



\faIcon{laptop-code} Software <!-- \faIcon{file-code} -->
=============================== 


<!-- ```{r sw_opt1} -->
<!-- # software %>% -->
<!-- #    vitae::detailed_entries( -->
<!-- #    what  = skills , -->
<!-- #     with =  area, -->
<!-- #     where = detail # -->
<!-- #   ) -->
<!-- #   -->
<!-- software %>% -->
<!--    vitae::detailed_entries( -->
<!--    what  = glue::glue("  {area}: [{skills}]") -->
<!--     #,where = detail # -->
<!--   ) -->

<!-- # software %>% -->
<!-- #    vitae::brief_entries( -->
<!-- #    what  = area , -->
<!-- #     with =  skills -->
<!-- #       -->
<!-- #   ) -->
<!-- ``` -->


```{r  sw_opt2, results='markup'}
# Lorena Abad, ma non viene !
# https://github.com/loreabad6/R-CV/blob/master/CV.Rmd

tribble(
   ~`Statistics / Databases`, ~`GIS`, ~`Other`,
  "R, RStudio, Stata, SQL, Salesforce, MS Excel",
  "ArcGIS, QGIS, GeoDa, OpenStreetMap",
  "Git, Github, Unix Shell, CSS, HTML, LaTeX, Markdown"
)  %>%
  kable(booktabs = T, align = 'c', escape = F, format = "latex")  %>%
  kable_styling(full_width = F, font_size = 10, latex_options = "HOLD_position") %>%
  row_spec(0, bold = T, color = "#009acd") |>
  row_spec(1, bold = F, color = "#7f7f7f") |>
  column_spec(column = 1:3, width = '4.75cm')
```


\faIcon{globe} Languages
==================================

<!-- ```{r lan_opt1} -->
<!-- languages %>%  -->
<!--   vitae::detailed_entries( -->
<!--     what = glue::glue("{area}: [{skills}]")  -->
<!--     ) -->
<!-- ``` -->

```{r lan_opt2, results='markup'}
data.frame(
  Skill = c("Reading", "Writing", "Listening","Speaking"),
  Italian = cell_spec(c(rep("Native", 4)), 'latex', color = '#005c7b'), 
  English = cell_spec(c("C2","C2","C2","C2"), 'latex', color = '#009acd'), 
  Spanish = cell_spec(c("C2","C1","C2","C2"), 'latex', color = '#4cb8dc'), 
  Portuguese = cell_spec(c("B2","A1","B2","B2"), 'latex', color = '#4cb8dc')
  #French = cell_spec(c("A2","A1","A1","A1"), 'latex', color = '#7fcce6') 
)  %>% 
  kable(booktabs = T, align = 'c', escape = F, format = "latex")  %>% 
  kable_styling(full_width = F, font_size = 10, latex_options = "HOLD_position") %>%  
  footnote(
    footnote_as_chunk = T,
    general_title = " ",
    general = "\\\\tiny Common European Framework of Reference for Languages: A1/A2: Basic User. B1/B2: Independent User. C1/C2: Proficient User",
    escape = F
  )  %>% 
  column_spec(column = 1:6, width = '2.4cm') #|> 
  # add_header_above(' ', line = F) |>
  # row_spec(0:4, extra_latex_after = "\\arrayrulecolor{white}") 
```


<!-- \faIcon{lightbulb}  Other Professional Service -->
<!-- ===================================== -->
<!-- ```{r} -->
<!-- # service <- tribble( ~what, ~when, ~with, -->
<!-- #   "Peer Reviewer",                "ongoing",                   "Energy Policy & Journal of the Association of Environmental -->

<!--   service %>% -->
<!--   vitae::detailed_entries( -->
<!--   what = what, -->
<!--   when =  when, -->
<!--   why = why -->
<!--   ) -->

<!-- ``` -->


<!-- \newpage -->

<!-- \faIcon*{pencil} Professional Development -->
<!-- =========================== -->

<!-- ```{r corsi_opt1} -->
<!-- # ---- OPTION 1 - with CERTIFICATES links -->
<!-- # courses <- tribble(~accomplishment,      ~year,     ~detail) -->
<!-- courses %>% -->
<!--   filter(year > 2014) %>% # mainly to stick to 2 pg -->
<!--   vitae::detailed_entries( -->
<!--     what = accomplishment, -->
<!--     when = year , -->
<!--     why = detail, # certificate -->
<!--     .protect = FALSE # allows links in column -->
<!--   ) -->

<!-- ``` -->


<!-- ```{r corsi_opt2} -->
<!-- # ---- OPTION 2 - withOUT CERTIFICATES links -->
<!-- # courses <- tribble(~accomplishment,      ~year,     ~detail) -->
<!-- courses %>%  -->
<!--   filter(year > 2014) %>% # mainly to stick to 2 pg  -->
<!--   vitae::detailed_entries( -->
<!--     what = accomplishment, -->
<!--     when = year , -->
<!--    # why = detail, # certificate  -->
<!--     .protect = FALSE # allows links in column -->
<!--   )  -->
<!-- ``` -->



```{r eval=FALSE, include=FALSE}
# To update CV on my website, run the following code in the console:
rmarkdown::render(here::here("03_CV_vitae", "awesome_resume_europrogettista.Rmd"), output_file = "../../../Documents/04_JOB/04_1_JobAppli/ShortCV_LMM.pdf")
```

```{r copyTOCVDIR, message=FALSE, warning=FALSE, include=FALSE}
# here::here()
# 
# # ObjectiFY SubDirs	
# from.dir <- "./content/cv/cv_making/resume_twentysecond"
# fs::path_abs(from.dir)
# 
# to.dir   <- "./content/cv"
# fs::path_abs(to.dir)
# 
# # List Files 
# files <- list.files(path = from.dir, 
# 						  pattern='\\.pdf$', # an optional regular expression. (ends with
# 						  full.names = TRUE, # If TRUE, the directory path is prepended to the file names 
# 						  recursive = FALSE) # Should the listing recurse into directories?
# 	
# # all_munge <- list.files(path = "./03_Munge/", pattern = '\\.R$' , 
# #                         all.files = FALSE,  # def (= only visible)
# #                         full.names = FALSE, # def (= no dir name prepended)
# #                         recursive = FALSE,  # def  (= no inside sub-dir )
# #                         ignore.case = TRUE, #    (= pattern-matching be case-insensitive)
# #                         include.dirs = FALSE, # def (subdirectory names NOT be included in recursive listings)
# #                         no.. = FALSE) # def (both "." and ".." be excluded also from non-recursive listings)
# class(files) 
# 
# # function to MOVE
# for (f in files) file.copy(from = f, to = to.dir,	 overwrite = T, copy.date = T)
```


